import { buildSync } from 'esbuild';
import fs from 'fs';
import path from 'path';

// Step 1: Compile the TypeScript theme file to JavaScript in memory
const result = buildSync({
	entryPoints: ['src/config/theme/theme.ts'],
	bundle: true,
	platform: 'node',
	write: false,
	format: 'cjs',
});

const compiled = result.outputFiles[0].text;

// Step 2: Emulate CommonJS and execute compiled code
const module = { exports: {} };
const func = new Function('module', 'exports', compiled);
func(module, module.exports);

// Step 3: Extract the theme object
// @ts-ignore
const theme = module.exports.default || module.exports.theme || module.exports;

if (!theme) {
	console.error('Theme format invalid or missing colors');
	process.exit(1);
}

// Step 4: Generate CSS variables
let css = '/* Do not edit this file, this will be automatically replaced by system */\n@import "tailwindcss";\n@custom-variant dark (&:where(.dark, .dark *));\n\n@theme {\n';

const flatten = (prefix, value) => {
	if (Array.isArray(value)) {
		value.forEach((v, i) => {
			css += `    --${prefix}-${i}: ${v};\n`;
		});
	} else if (typeof value === 'object') {
		Object.entries(value).forEach(([k, v]) => {
			flatten(`${prefix}-${k}`, v);
		});
	} else {
		css += `    --${prefix}: ${value};\n`;
	}
};

for (const [key, value] of Object.entries(theme)) {
	flatten(key, value);
}

css += '}';

// Step 5: Write to file
const outputPath = path.join('src', 'tailwind.css');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, css);

console.log('✅ Tailwind theme generated at:', outputPath);

